site_name: Zhonghui
site_url: https://www.gzher.com/

plugins: []

nav:
    - Home: index.md
    - Wiki: https://wiki.gzher.com
    - Library: https://lib.gzher.com
    - Webdav: https://dav.gzher.com
    - Mail: mailto:mail@gzher.com
    - Github: https://github.com/GZhonghui
    - Dropbox: https://www.dropbox.com
    - Notion: https://www.notion.so

extra_css:
    - css/extra.css